<a href="https://colab.research.google.com/github/nitinpatil301a/Tensorflow-Keras-Work/blob/master/data_augmentation_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.0.0
import tensorflow as tf
print(tf.__version__)
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense, Conv2D, MaxPool2D, ZeroPadding2D, Dropout, BatchNormalization
from tensorflow.keras.preprocessing.image import ImageDataGenerator,img_to_array,load_img

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.0.0`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.
2.2.0-rc2


In [2]:
!git clone https://github.com/nitinpatil301a/Tensorflow-Keras-Work.git

fatal: destination path 'Tensorflow-Keras-Work' already exists and is not an empty directory.


In [0]:
datagen=ImageDataGenerator(rotation_range=40,
                           zoom_range=0.2,
                           vertical_flip=True,
                           horizontal_flip=True,
                           width_shift_range=0.2,
                           height_shift_range=0.2,
                           shear_range=0.2)

img=load_img('/content/Tensorflow-Keras-Work/cat.jpg',target_size=(150,150,3))

In [0]:
x=img_to_array(img)
x=np.reshape(x,(1,150,150,3))

In [5]:
x.shape

(1, 150, 150, 3)

In [6]:
i=0
for batch in  datagen.flow(x,save_to_dir='/content/Tensorflow-Keras-Work/',save_prefix='cat',):
  print(batch)
  i+=1
  if(i==10):
    break

[[[[ 40.351166  37.021397  32.68093 ]
   [ 49.37055   45.5516    42.1895  ]
   [ 55.838337  54.741337  52.709003]
   ...
   [ 41.04709   87.61772   29.047089]
   [ 40.41545   86.03863   28.415453]
   [ 39.783813  84.56763   27.891907]]

  [[ 39.204266  35.64512   31.763412]
   [ 47.306133  43.716564  39.895702]
   [ 54.691437  52.9063    50.64459 ]
   ...
   [ 39.37678   83.75356   27.68839 ]
   [ 38.745144  82.49029   27.372572]
   [ 38.113506  81.22701   27.056753]]

  [[ 38.057365  34.26884   30.845894]
   [ 45.241714  41.881523  37.601906]
   [ 53.54454   51.071262  48.58017 ]
   ...
   [ 37.11941   79.82588   25.238821]
   [ 35.2245    77.29933   21.449001]
   [ 33.32959   74.77279   17.65918 ]]

  ...

  [[216.44891  210.08669  196.63002 ]
   [215.1347   208.8653   195.      ]
   [215.45053  208.54947  195.      ]
   ...
   [179.446    194.39297  193.92912 ]
   [226.16086  225.4945   215.54193 ]
   [228.28146  226.01987  215.39238 ]]

  [[215.65404  208.34596  195.      ]
   [215